<a href="https://colab.research.google.com/github/rautbibek123/DataScience_MachineLearning/blob/main/DSML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Helloworld")

Helloworld


#Python Basic


In [ ]:
x=5
y="Bibek"
print(x)
print(y)

5
Bibek


In [ ]:
name="multimedia"
print("name:",name)

name: multimedia


**DATA TYPES**

In [ ]:
x=5.1
print(type(x))

<class 'float'>


In [ ]:
list1 = [1,2,3,4,5,6]
print(list1)
print(list1[0])
print(list1[1])
print(list1[2])
print(list1[-1])
print(type(list1))

[1, 2, 3, 4, 5, 6]
1
2
3
6
<class 'list'>


In [ ]:
list1 = [1,2,3,4,5,6]
print("List:",list1)
print("Using INdex: 0 5 -1:",list1[0],list1[5],list1[-1])
print("Length of list:",list1)

List: [1, 2, 3, 4, 5, 6]
Using INdex: 0 5 -1: 1 6 6
Length of list: [1, 2, 3, 4, 5, 6]


In [ ]:
#APPEND ITME LIST
thislist = ["apple", "banana", "cherry"]
print(thislist)
thislist.append("orange")
print(thislist)

['apple', 'banana', 'cherry']
['apple', 'banana', 'cherry', 'orange']


In [ ]:
#REMOVE THE ITME
thislist = ["apple", "banana", "cherry"]
print(thislist)
thislist.remove("banana")
print(thislist)

['apple', 'banana', 'cherry']
['apple', 'cherry']


In [ ]:
#DISPLAY THE ITEM
thislist = ["apple", "banana", "cherry"]
for x in thislist:
  print(x)

apple
banana
cherry


In [ ]:
#FOR LOOP IN PYTHON
# for(i=0; i<=10; i++)
for i  in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#SORTING
thislist = [100, 50, 65, 82, 23]
thislist.sort()
print(thislist)

[23, 50, 65, 82, 100]


In [ ]:
#SORTING
thislist = ["Apple","banana","kiwi","orange"]
thislist.sort(reverse = True)
print(thislist)

['orange', 'kiwi', 'banana', 'Apple']


In [ ]:
#JOIN TWO LIST
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

list3 = list1 + list2
print(list3)

['a', 'b', 'c', 1, 2, 3]


In [ ]:
#DICTIONARIES
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [ ]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict["brand"])
model=thisdict["model"]

Ford


In [ ]:
#FOR LOOPS IN PYTHON
for i in range (10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
a=10
b=15
if a>b:
  print("a is greater than b")
else:
  print("a is less than b")

a is less than b


In [ ]:
def my_function():
  print("Hello from a function")

my_function()

Hello from a function


In [ ]:
def my_function(fname):
  print(fname + " empty")

my_function("Email")
my_function("Tobias")
my_function("Linus")

Email empty
Tobias empty
Linus empty


In [ ]:
#PYTHON FUNCTION
def print_name(full_name,ward_name):
  print("Name:",full_name,"Ward:",ward_name)

print_name("Bibek Raut",10)

Name: Bibek Raut Ward: 10


In [ ]:
!pip install numpy


In [ ]:
#creating array of zeros
import numpy as np
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#evenly spaced array
np.arange(10,25,5)

array([10, 15, 20])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
import numpy as np
a=np.linspace(0,10,100)
print(a)

[ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.18181818  8

In [ ]:
#numpy.random.randint(low , high=none)
import numpy as np
a=np.random.randint(5,10,3)
print(a)

[7 5 6]


In [ ]:
#create array of shape (4,5)
import numpy as np
a=np.random.rand(4,5)
print(a)

[[0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
 [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]
 [0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]]


In [ ]:
#create array of shape (4,5)
#with the random value between 0 to 1
import numpy as np
np.random.seed(42)
a=np.random.rand(4,5)
print(a)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]]


In [ ]:
!pip install pandas

In [ ]:
#creating dataframe: using List
import pandas as pd
list=["apple","orange","mango"]
df=pd.DataFrame(list)
print(df)

        0
0   apple
1  orange
2   mango


In [ ]:
#creating dataframe: using List
import pandas as pd
list=["apple","orange","mango"]
df=pd.DataFrame(list, columns=["fruits"])
print(df)

   fruits
0   apple
1  orange
2   mango


In [ ]:
#initilize data of lists
data={'Name':['Tom','nick','krish','jack'],
      'Age':[20,21,19,18]}
#create data frame
df=pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18


In [ ]:
#columns selection
import pandas as pd
data={'Name':['Tom','nick','krish','jack'],
      'Age':[20,21,19,18],
      'address':['jnk','pkr','npl','ipl']}
#create data frame
df=pd.DataFrame(data)
#select two columns
print(df[['address','Age']])

  address  Age
0     jnk   20
1     pkr   21
2     npl   19
3     ipl   18


In [ ]:
import pandas as pd

# Create sample data
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 28],
    'address':['jnk','pkr','npl']
}

# Save to CSV
df = pd.DataFrame(data)
df.to_csv('data.csv', index=False)  # Save without the index column

# Read from CSV
df = pd.read_csv('data.csv')
print(df)


      Name  Age address
0    Alice   25     jnk
1      Bob   30     pkr
2  Charlie   28     npl


In [ ]:
#Read data using csv reader
import pandas as pd
df=pd.read_csv('data.csv')
print(df)

      Name  Age address
0    Alice   25     jnk
1      Bob   30     pkr
2  Charlie   28     npl
